$.validator.setDefaults({
    submitHandler: function(form) {
      form.submit();
    }
});
$().ready(function() {
    $("#formValidate").validate({
    	rules:{
    	 	qyname:{
    			required:true,
    		},
    		qycode:{
    			required:true,
    		},
    		jyaddress:{
    			required:true,
    		},
    		addressjd:{
    			required:true,
    		},
    		addresswd:{
    			required:true,
    		},
    		legal:{
    			required:true,
    		},
    		idpapers:{
    			required:true,
    			digits:true
    		},
    		gdphone:{
    			required:true,
    		},
    		phone:{
    			required:true,
    			digits:true
    		},
    		yybusiness:{
    			required:true,
    		},
    		xkbusiness:{
    			required:true,
    		},
    		qbusiness:{
    			required:true,
    		},
    		zbusiness:{
    			required:true,
    		},
    		jyscope:{
    			required:true,
    		},
    		spsafety:{
    			required:true,
    		},
    		lxphone:{
    			required:true,
    			digits:true
    		},
    		tjnumber:{
    			required:true,
    			digits:true
    		},
    		zgnumber:{
    			required:true,
    			digits:true
    		},
    		jjproperties:{
    			required:true,
    		},
    		ztmanner:{
    			required:true,
    		},
    		jyarea:{
    			required:true,
    		},
    		shcode:{
    			required:true,
    		},
    		material:{
    			required:true,
    		},
    		remark:{
    			required:true,
    		}
    	},
    	message:{
    		qyname:{
    			required:"必须填写"
			},
			qycode:{
				required:"必须填写"
			}
    	}
    });
});