$.validator.setDefaults({
    submitHandler: function(form) {
      form.submit();
    }
});
$().ready(function() {
    $("#formValidate").validate({
    	rules:{
    	 	qyname:{
    			required:true,
    		},
    		address:{
    			required:true,
    		},
    		scaddress:{
    			required:true,
    		},
    		ems:{
    			required:true,
    		},
    		phone:{
    			required:true,
    		},
    		fax:{
    			required:true,
    		},
    		email:{
    			required:true,
    			digits:true
    		},
    		zzcode:{
    			required:true,
    		},
    		jjtype:{
    			required:true,
    			digits:true
    		},
    		gsorganization:{
    			required:true,
    		},
    		yylicense:{
    			required:true,
    		},
    		cldate:{
    			required:true,
    		},
    		jyqxdate:{
    			required:true,
    		},
    		gdfund:{
    			required:true,
    		},
    		zcfund:{
    			required:true,
    		},
    		nzyield:{
    			required:true,
    			digits:true
    		},
    		nxlimit:{
    			required:true,
    			digits:true
    		},
    		njmoney:{
    			required:true,
    			digits:true
    		},
    		nfund:{
    			required:true,
    		},
    		qyscale:{
    			required:true,
    		},
    		fddelegate:{
    			required:true,
    		},
    		fdphone:{
    			required:true,
    		},
    		qydelegate:{
    			required:true,
    		},
    		qyphone:{
    			required:true,
    		},
    		zldelegate:{
    			required:true,
    		},
    		zlphone:{
    			required:true,
    		},
    		spdelegate:{
    			required:true,
    		},
    		spphone:{
    			required:true,
    		},
    		assay:{
    			required:true,
    		},
    		assayphone:{
    			required:true,
    		},
    		cynumber:{
    			required:true,
    		},
    		zynumber:{
    			required:true,
    		},
    		fzdate:{
    			required:true,
    		},
    		scpermit:{
    			required:true,
    		},
    		scpermitdate:{
    			required:true,
    		},
    		department:{
    			required:true,
    		},
    		cpstandard:{
    			required:true,
    		},
    		records:{
    			required:true,
    		},
    		product:{
    			required:true,
    		}
    }
    });
});